version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
      environment:
        TEST_DATABASE_URL: postgresql://root@localhost/circle_test
          
    # Service container image
      - image: circleci/postgres:9.6.5-alpine-ram
        
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: sudo apt install -y postgresql-client || true
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate
      # - save_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      #     paths:
      #       - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app