version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: postgres:9.6-jessie
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: db_name
          DB_HOST: 127.0.0.1
    steps:
      - checkout
      # - restore_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
        environment:
          DATABASE_URL: "postgres://ubuntu@127.0.0.1:5432/db_name"
      # - save_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      #     paths:
      #       - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py migrate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app