version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies in a env
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - env
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            echo $pwd
            . env/bin/activate
            python3 manage.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test