# Generated by Django 3.0.5 on 2020-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
