# Generated by Django 3.0.5 on 2020-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20200413_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(help_text='Markdown is supported'),
        ),
    ]
