# Generated by Django 3.0.5 on 2020-04-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20200413_1322'),
        ('note', '0002_auto_20200411_1849'),
    ]

    operations = [
    ]
