# Generated by Django 3.0.5 on 2020-04-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=20)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('old', 'Old Testament'), ('new', 'New Testament')], default='old', max_length=5)),
            ],
        ),
    ]
