# Generated by Django 3.0.5 on 2020-04-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bible',
            options={'ordering': ['id']},
        ),
    ]
