# Generated by Django 3.0.5 on 2020-04-04 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20200404_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bible.Bible')),
            ],
        ),
    ]
