# Generated by Django 3.0.5 on 2020-04-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_verseoftheday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bible',
            options={'ordering': ['id'], 'verbose_name_plural': 'Bible'},
        ),
        migrations.AlterModelOptions(
            name='verseoftheday',
            options={'ordering': ['id'], 'verbose_name_plural': 'Verse of the day'},
        ),
    ]
