name: Danger
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: danger/danger@master
      env:
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
