# This is a basic workflow to help you get started with Actions

name: Django deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
        
    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev
      
    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run test
      run: |
        python manage.py makemigrations --noinput
        python manage.py migrate
        python manage.py test --keepdb
        
      env:
        SECRET_KEY: "testkey"
        ENV: "production"
        DATABASE_URL: "postgres://postgres:@localhost:5432/biblelover_test" 
